import Image from "next/image";
import { ArrowRight, Check, Compass, Mail, MessageCircle, PackageCheck, Phone, Route, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { ProductCard } from "@/components/product-card";
import { products, services, site } from "@/lib/site";

export function Hero(){return <section className="signal-grid relative overflow-hidden bg-ink text-white"><span className="signal-line absolute left-[56%] top-0 h-full w-px bg-brass/50" aria-hidden="true"/><div className="container-page relative z-10 grid min-h-[calc(100vh-64px)] items-center gap-10 py-12 lg:grid-cols-[0.82fr_1.18fr] lg:py-16"><div><p className="eyebrow text-brass">Trade Intelligence, Made Practical</p><h1 className="mt-5 max-w-3xl text-5xl font-bold leading-[1.02] sm:text-6xl lg:text-7xl">Make every trade conversation count.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-white/70">KKL TRADING CO., LTD. brings product sourcing, commercial coordination, and partner dialogue into one more focused starting point.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button href="/showcase">Explore the Trade Desk <ArrowRight size={18}/></Button><Button href="/contact" variant="secondary">Open an Inquiry</Button></div><div className="mt-9 grid grid-cols-3 gap-4 border-t border-white/15 pt-6 text-sm">{["Market aware","Program led","Partner ready"].map(item=><div key={item} className="flex items-start gap-2 font-semibold text-white/70"><Check size={16} className="mt-0.5 shrink-0 text-brass"/>{item}</div>)}</div></div><div className="relative"><div className="absolute -left-4 top-8 z-10 hidden border border-brass/40 bg-ink p-4 shadow-soft md:block"><p className="text-xs font-bold uppercase tracking-widest text-brass">KKL TRADE SIGNAL</p><p className="mt-1 text-sm font-bold">Ontario / Global Reach</p></div><div className="absolute -bottom-4 right-4 z-10 hidden bg-wine px-4 py-3 text-xs font-bold text-white shadow-soft md:block">CLARITY / COORDINATION / PROGRESS</div><div className="overflow-hidden border border-white/15 shadow-soft"><Image src="/images/hero.png" alt="Containers at an intermodal trade terminal" width={1536} height={864} priority className="h-auto w-full"/></div></div></div></section>}

export function ProductGrid({limit}:{limit?:number}){const visible=limit?products.slice(0,limit):products;return <section className="bg-pearl py-20"><div className="container-page"><p className="eyebrow text-wine">Trade Desk</p><h2 className="mt-3 max-w-3xl text-4xl font-bold text-ink">The intelligence behind a stronger trade program.</h2><p className="mt-4 max-w-3xl leading-7 text-ink/65">These representative focus areas are modular by design. They create a professional starting point for approved product directions, sourcing needs, and commercial partner discussions without presenting a live shopping catalog.</p><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{visible.map(product=><ProductCard key={product.name} product={product}/>)}</div></div></section>}

export function TrustBand(){const items=[{icon:Compass,title:"Signal-led",text:"Start with the market question, the product brief, and the context that makes an opportunity worth pursuing."},{icon:Route,title:"Operationally clear",text:"Bring sourcing, quality, timing, delivery, and coordination into a conversation that can move forward."},{icon:ShieldCheck,title:"Built for confidence",text:"A search-ready public introduction for buyers, suppliers, and commercial partners."}];return <section className="bg-mist py-14"><div className="container-page grid gap-5 md:grid-cols-3">{items.map(item=><div key={item.title} className="border border-ink/10 bg-white p-6"><item.icon className="text-wine" size={24}/><h3 className="mt-4 text-lg font-bold text-ink">{item.title}</h3><p className="mt-2 text-sm leading-6 text-ink/65">{item.text}</p></div>)}</div></section>}

export function ServicesSection(){return <section className="bg-ink py-20 text-white"><div className="container-page grid gap-10 md:grid-cols-[0.85fr_1.15fr] md:items-center"><div><p className="eyebrow text-brass">Working Model</p><h2 className="mt-3 text-4xl font-bold">Less friction. Better visibility.</h2><p className="mt-5 max-w-md leading-7 text-white/70">KKL is structured for qualified sourcing, commercial, and trade partnership conversations across changing markets.</p><Button href="/services" className="mt-7">Explore Capabilities</Button></div><div className="grid gap-3 sm:grid-cols-2">{services.map(service=><div key={service} className="flex gap-3 border-l-2 border-brass bg-white/5 p-4 text-sm font-semibold text-white/85"><Check size={18} className="mt-0.5 shrink-0 text-brass"/>{service}</div>)}</div></div></section>}

export function ContactSection(){return <section className="bg-white py-20"><div className="container-page grid gap-10 md:grid-cols-2"><div><p className="eyebrow text-wine">Contact KKL</p><h2 className="mt-3 text-4xl font-bold text-ink">Bring a practical question.</h2><p className="mt-5 max-w-md leading-7 text-ink/70">Tell us what you are looking to source, coordinate, or explore, and include the market context or product direction when you can.</p><div className="mt-8 grid gap-4 text-sm font-semibold text-ink/80"><a href={`mailto:${site.email}`} className="flex items-center gap-3"><Mail className="text-wine" size={18}/>{site.email}</a><a href={`tel:${site.phone.replace(/[^+\d]/g, "")}`} className="flex items-center gap-3"><Phone className="text-wine" size={18}/>{site.phone}</a><a href={`https://wa.me/${site.whatsapp.replace("+","")}`} className="flex items-center gap-3"><MessageCircle className="text-wine" size={18}/>WhatsApp trade inquiry</a></div></div><form className="border border-ink/15 bg-pearl p-6"><label className="grid gap-2 text-sm font-bold">Name<input className="focus-ring min-h-12 border border-ink/15 bg-white p-3" placeholder="Your name"/></label><label className="mt-4 grid gap-2 text-sm font-bold">Business email<input className="focus-ring min-h-12 border border-ink/15 bg-white p-3" placeholder="you@company.com"/></label><label className="mt-4 grid gap-2 text-sm font-bold">Trade interest<input className="focus-ring min-h-12 border border-ink/15 bg-white p-3" placeholder="Sourcing, supply, distribution, partnership..."/></label><label className="mt-4 grid gap-2 text-sm font-bold">Message<textarea className="focus-ring min-h-32 border border-ink/15 bg-white p-3" placeholder="Share the opportunity or requirement."/></label><Button href={`mailto:${site.email}?subject=KKL%20Trading%20Inquiry`} className="mt-5 w-full">Send Inquiry</Button></form></div></section>}
