import Image from "next/image";
import { ArrowDownRight, ArrowUpRight, Mail, MessageCircle, Phone } from "lucide-react";
import { Button } from "@/components/ui/button";
import { products, services, site } from "@/lib/site";

export function Hero() {
  return <section className="bg-pearl text-ink"><div className="container-page grid gap-0 border-x border-ink/15 lg:grid-cols-[1.12fr_0.88fr]"><div className="fieldbook-grid border-b border-ink/15 px-6 py-10 lg:border-b-0 lg:border-r lg:px-12 lg:py-14"><div className="flex items-center justify-between text-[11px] font-bold uppercase"><span>KKL Trade Fieldbook</span><span className="text-wine">No. 01 / 2026</span></div><h1 className="mt-12 max-w-2xl font-serif text-5xl leading-[0.98] sm:text-6xl lg:text-6xl">Trade, with more to go on.</h1><p className="mt-6 max-w-lg text-base leading-7 text-ink/75">A practical trading desk for sourcing questions, commercial programs, and partner conversations that deserve a clearer next step.</p><div className="mt-8 flex flex-wrap items-center gap-x-6 gap-y-4 text-sm font-bold"><a href="/showcase" className="trade-link">Open the trade index <ArrowUpRight className="ml-1 inline" size={16}/></a><a href="/contact" className="trade-link text-wine">Send an inquiry</a></div><div className="mt-10 grid max-w-lg grid-cols-2 gap-5 border-t border-ink/15 pt-4 text-xs leading-5 text-ink/60"><div><p className="font-bold uppercase text-wine">Trade note</p><p className="mt-1">Ontario corporation for international trade and commercial collaboration.</p></div><div className="border-l border-ink/15 pl-5"><p className="font-bold uppercase text-wine">Inquiry desk</p><p className="mt-1">Sourcing, programs, and partner dialogue.</p></div></div></div><div className="relative min-h-[360px] overflow-hidden bg-ink lg:min-h-[520px]"><Image src="/images/hero.png" alt="Trade research materials and container shipping references" fill priority className="trade-image object-cover object-[58%_center]"/><div className="absolute inset-x-0 bottom-0 grid grid-cols-[1fr_auto] items-end gap-4 border-t border-white/20 bg-ink/90 p-5 text-white lg:p-7"><div><p className="text-xs font-bold uppercase text-white/65">Program log</p><p className="mt-2 max-w-xs font-serif text-xl leading-tight">From market signal to operational direction.</p></div><span className="hidden border border-white/50 px-3 py-2 text-[10px] font-bold uppercase sm:block">Active desk</span></div></div></div></section>;
}

export function ProductGrid() {
  return <section className="bg-pearl py-20"><div className="container-page"><div className="flex flex-col justify-between gap-6 border-y border-ink/15 py-5 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase text-wine">01 / Trade Index</p><h2 className="mt-3 max-w-2xl font-serif text-4xl leading-tight">The questions behind every program.</h2></div><p className="max-w-sm text-sm leading-6 text-ink/65">Representative areas for collaboration. They are not a fixed product catalog and can be refined around approved programs.</p></div><div className="mt-10 grid gap-0 border-l border-t border-ink/15 md:grid-cols-2 xl:grid-cols-3">{products.map((item, index) => <article key={item.name} className="group border-b border-r border-ink/15 bg-pearl"><div className="relative aspect-[4/3] overflow-hidden bg-mist"><Image src={item.image} alt={`${item.name} trade program`} fill className="trade-image object-cover transition duration-700 group-hover:scale-105"/></div><div className="p-6"><p className="text-xs font-bold uppercase text-wine">{String(index + 1).padStart(2, "0")} / {item.category}</p><h3 className="mt-7 font-serif text-2xl leading-tight">{item.name}</h3><p className="mt-3 text-sm leading-6 text-ink/70">{item.description}</p><div className="mt-6 flex flex-wrap gap-2">{item.tags.map(tag => <span key={tag} className="border border-ink/20 px-2 py-1 text-[10px] font-bold uppercase">{tag}</span>)}</div></div></article>)}</div></div></section>;
}

export function TrustBand() {
  return <section className="bg-ink py-20 text-white"><div className="container-page"><div className="grid gap-8 border-b border-white/20 pb-8 md:grid-cols-[0.8fr_1.2fr]"><p className="text-xs font-bold uppercase tracking-[0.16em] text-blush">02 / Route Index</p><h2 className="max-w-3xl font-serif text-4xl leading-tight">The route is not a promise. It is a way to make the next decision visible.</h2></div><div className="relative mt-12 grid gap-8 md:grid-cols-3"><svg className="pointer-events-none absolute left-[16%] top-7 hidden h-8 w-[68%] md:block" viewBox="0 0 600 30" fill="none" aria-hidden="true"><path className="route-dash" d="M0 15H600" stroke="#F1DBC7" strokeWidth="1"/></svg>{[["Brief","Define the product question, commercial context, and the signal worth following."],["Align","Bring sourcing, specifications, quality, timing, and partner roles into view."],["Move","Coordinate the next practical step with more shared understanding."]].map(([title,text],index)=><div key={title} className="relative"><span className="grid size-14 place-items-center border border-blush/60 bg-ink font-serif text-xl text-blush">0{index + 1}</span><h3 className="mt-8 font-serif text-3xl">{title}</h3><p className="mt-3 max-w-xs text-sm leading-6 text-white/65">{text}</p></div>)}</div></div></section>;
}

export function ServicesSection() {
  return <section className="bg-mist py-20"><div className="container-page grid gap-10 lg:grid-cols-[0.78fr_1.22fr]"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-wine">03 / Working Desk</p><h2 className="mt-4 max-w-md font-serif text-4xl leading-tight">A place to make the practical parts legible.</h2><p className="mt-5 max-w-md leading-7 text-ink/70">KKL is built for qualified sourcing, commercial, and partnership conversations, not generic transactions.</p><a href="/services" className="mt-8 inline-block text-sm font-bold text-wine trade-link">View full capabilities <ArrowDownRight className="ml-1 inline" size={16}/></a></div><ol className="border-t border-ink/15">{services.map((service,index)=><li key={service} className="grid grid-cols-[52px_1fr_auto] items-center gap-4 border-b border-ink/15 py-5"><span className="font-serif text-xl text-wine">{String(index + 1).padStart(2, "0")}</span><span className="font-serif text-2xl leading-tight">{service}</span><ArrowUpRight size={18} className="text-ink/45"/></li>)}</ol></div></section>;
}

export function ContactSection() {
  return <section className="bg-wine py-20 text-white"><div className="container-page grid gap-12 md:grid-cols-[0.9fr_1.1fr]"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-blush">04 / Open Desk</p><h2 className="mt-4 max-w-md font-serif text-5xl leading-[0.95]">Bring the trade question with you.</h2><p className="mt-6 max-w-md leading-7 text-white/80">Share the product direction, market context, sourcing requirement, or partnership idea you want to move forward.</p><div className="mt-10 grid gap-4 text-sm font-bold"><a href={`mailto:${site.email}`} className="flex items-center gap-3"><Mail size={18}/>{site.email}</a><a href={`tel:${site.phone.replace(/[^+\d]/g, "")}`} className="flex items-center gap-3"><Phone size={18}/>{site.phone}</a><a href={`https://wa.me/${site.whatsapp.replace("+", "")}`} className="flex items-center gap-3"><MessageCircle size={18}/>WhatsApp trade inquiry</a></div></div><form className="bg-pearl p-6 text-ink"><p className="text-xs font-bold uppercase tracking-[0.14em] text-wine">Inquiry note</p><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-sm font-bold">Name<input className="focus-ring min-h-12 border-b border-ink/30 bg-transparent px-0" placeholder="Your name"/></label><label className="grid gap-2 text-sm font-bold">Business email<input className="focus-ring min-h-12 border-b border-ink/30 bg-transparent px-0" placeholder="you@company.com"/></label></div><label className="mt-5 grid gap-2 text-sm font-bold">Trade interest<input className="focus-ring min-h-12 border-b border-ink/30 bg-transparent px-0" placeholder="Sourcing, supply, distribution, partnership..."/></label><label className="mt-5 grid gap-2 text-sm font-bold">Message<textarea className="focus-ring min-h-32 border-b border-ink/30 bg-transparent p-0" placeholder="Share the opportunity or requirement."/></label><Button href={`mailto:${site.email}?subject=KKL%20Trading%20Inquiry`} className="mt-7 w-full">Send inquiry</Button></form></div></section>;
}
