export const site={name:"KKL TRADING",legalName:"KKL TRADING CO., LTD.",url:"https://kkltrading.org",email:"info@kkltrading.org",phone:"+1 (289) 555-0148",whatsapp:"+12895550148",address:{city:"Mississauga",state:"Ontario",country:"Canada"}};
export const navItems=[{label:"Home",href:"/"},{label:"About",href:"/about"},{label:"Capabilities",href:"/services"},{label:"Trade Desk",href:"/showcase"},{label:"Contact",href:"/contact"}];
export const products=[
{name:"Opportunity Discovery",category:"Trade Intelligence",image:"/images/discovery.png",description:"A useful first conversation around the market context, product need, and commercial opportunity worth exploring.",tags:["Discovery","Markets","Fit"]},
{name:"Product Sourcing",category:"Supply Direction",image:"/images/sourcing.png",description:"Focused dialogue around product direction, sourcing requirements, and the information needed to define a program.",tags:["Sourcing","Research","Briefs"]},
{name:"Supplier Alignment",category:"Operations",image:"/images/operations.png",description:"A structured lens for supplier, specification, timing, and operational planning conversations.",tags:["Suppliers","Planning","Operations"]},
{name:"Quality Readiness",category:"Review",image:"/images/quality.png",description:"Practical readiness discussions for samples, specifications, quality expectations, and program confidence.",tags:["Quality","Samples","Review"]},
{name:"Market Programs",category:"Commercial",image:"/images/market.png",description:"Commercial planning support for evolving market opportunities, channel context, and program shape.",tags:["Markets","Programs","Commercial"]},
{name:"Partnership Development",category:"Collaboration",image:"/images/partnership.png",description:"Clear dialogue for connecting commercial interests, partner roles, and the right next step.",tags:["Partners","Trade","Growth"]},
{name:"Fulfillment Planning",category:"Logistics",image:"/images/fulfillment.png",description:"Early-stage coordination around shipping, delivery expectations, and the operational path ahead.",tags:["Logistics","Delivery","Flow"]},
{name:"Program Coordination",category:"Execution",image:"/images/coordination.png",description:"A practical view of the details, communication points, and timelines that keep a trade program moving.",tags:["Coordination","Timelines","Execution"]},
{name:"Commercial Roadmaps",category:"Progress",image:"/images/roadmap.png",description:"A structured path from initial inquiry to a more defined commercial conversation and next action.",tags:["Roadmaps","Progress","Clarity"]},
{name:"Future Trade Lines",category:"Possibility",image:"/images/future.png",description:"A flexible area for emerging product directions, new partner conversations, and future approved trade programs.",tags:["Future","Programs","Opportunity"]}];
export const services=["Trade opportunity discovery","Product sourcing and brief development","Supplier and program coordination","Sample, quality, and readiness discussions","Commercial market planning","Fulfillment and partner coordination"];
